name: Check Required Secrets and Environment Variables

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-config:
    name: Validate Env & Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Check required secrets
        run: |
          REQUIRED_SECRETS=("AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY")
          MISSING=0
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[secret] }}" ]; then
              echo "❌ Missing required secret: $secret"
              MISSING=1
            else
              echo "✅ Found secret: $secret"
            fi
          done
          if [ "$MISSING" -eq 1 ]; then
            echo "::error::One or more required secrets are missing"
            exit 1
          fi

      - name: Check required environment variables
        run: |
          REQUIRED_ENVS=("AVAILABILITY_ZONE" "MAX_ECS_FARGATE_COUNT" "COST_ALERT_EMAIL")
          MISSING=0
          for env in "${REQUIRED_ENVS[@]}"; do
            if [ -z "${{ vars[env] }}" ]; then
              echo "❌ Missing required environment variable: $env"
              MISSING=1
            else
              echo "✅ Found variable: $env"
            fi
          done
          if [ "$MISSING" -eq 1 ]; then
            echo "::error::One or more required environment variables are missing"
            exit 1
          fi
