name: Check Environment Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        run: |
          REQUIRED_SECRETS=("AWS_ACCESS_KEY_ID" "AWS_SECRET_ACCESS_KEY" "AWS_REGION" "AWS_ACCOUNT_ID" "ECR_REPOSITORY")
          for secret in "${REQUIRED_SECRETS[@]}"; do
            if [ -z "${{ secrets[$secret] }}" ]; then
              echo "❌ Missing required secret: $secret"
              exit 1
            fi
          done
          echo "✅ All required secrets are set."
