name: Check Dockerfile After Secrets Check

on:
  workflow_run:
    workflows: ["Check Environment Secrets"]
    types:
      - completed

jobs:
  check-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "❌ No Dockerfile found!"
            exit 1
          fi
          echo "✅ Dockerfile found."
