name: Dockerfile Check & Build

on:
  workflow_run:
    workflows: ["Check Dockerfile After Merge"]
    types:
      - completed

jobs:
  check-dockerfile-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Check if Dockerfile exists
      - name: Verify Dockerfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "❌ No Dockerfile found in the root of the repository!"
            exit 1
          else
            echo "✅ Dockerfile found."
          fi

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=my-app
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Optional Step: List built images
      - name: List Docker Images
        run: docker images
